apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-datasource
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  tempo-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3100
        jsonData:
          tracesToMetrics:
            datasourceUid: prometheus
            tags: [{key: "service.name", value: "service"}]
          serviceMap:
            datasourceUid: prometheus