apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrieval-svc
  namespace: argus
spec:
  replicas: 2
  selector:
    matchLabels: {app: retrieval-svc}
  template:
    metadata:
      labels: {app: retrieval-svc}
    spec:
      serviceAccountName: argus-sa
      containers:
        - name: retrieval-svc
          image: 844074033173.dkr.ecr.ap-south-1.amazonaws.com/argus/retrieval-svc:latest
          imagePullPolicy: Always
          ports: [{containerPort: 8000}]
          env:
            - {name: CHROMA_HOST, value: "chromadb"}
            - {name: AWS_REGION, value: "ap-south-1"}
            - {name: VECTOR_BACKEND, value: "weaviate"}
            - {name: WEAVIATE_HTTP_HOST, value: "weaviate"}
            - {name: WEAVIATE_HTTP_PORT, value: "8080"}
            - {name: WEAVIATE_GRPC_PORT_NUM, value: "50051"}
          readinessProbe:
            httpGet: {path: /health, port: 8000}
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: {path: /health, port: 8000}
            initialDelaySeconds: 15
          resources:
            requests: {cpu: "100m", memory: "256Mi"}
            limits: {cpu: "500m", memory: "512Mi"}
---
apiVersion: v1
kind: Service
metadata:
  name: retrieval-svc
  namespace: argus
spec:
  selector: {app: retrieval-svc}
  ports: [{port: 8000, targetPort: 8000}]