apiVersion: v1
kind: Namespace
metadata:
  name: argus
 
---
apiVersion: v1
kind: Secret
metadata:
  name: argus-secrets
  namespace: argus
type: Opaque
stringData:
  POSTGRES_PASSWORD: "myh81dYXntr3QjF+l3uV5ZOTkS+vQHcQ"
  JWT_SECRET: "<generate-a-real-one>"