image:
  tag: 1.27.0

replicas: 1

storage:
  size: 20Gi
  storageClassName: gp2-retain

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

env:
  QUERY_DEFAULTS_LIMIT: 25
  AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
  PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
  DEFAULT_VECTORIZER_MODULE: "none"
  ENABLE_MODULES: ""
  CLUSTER_HOSTNAME: "weaviate-0"
  GRPC_PORT: "50051"          # <-- tell the container itself to actually listen on 50051

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
    - name: grpc
      port: 50051

grpcService:
  type: ClusterIP
  enabled: true
  name: weaviate-grpc
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051      # <-- explicit, don't rely on chart default